// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyB2uVN6SxP5ENHHLDWkOBgOCRptUxvvUtY',
      appId: '1:49238018761:web:3b036b6e94686a31e71b18',
      messagingSenderId: '49238018761',
      projectId: "boutiq-stage",
      authDomain: "boutiq-stage.firebaseapp.com",
      storageBucket: "boutiq-stage.appspot.com",
      measurementId: "G-2NH15J2BFS");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt98bKYFrSzETXHP_CQ09qIV2irWisB9o',
    appId: '1:49238018761:android:25b53cf4da848eeee71b18',
    messagingSenderId: '49238018761',
    projectId: 'boutiq-stage',
    storageBucket: "boutiq-stage.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYA3mqo2xFsY5264huhA_A9n6-VaD84a8',
    appId: '1:49238018761:ios:18a5fae92089122ae71b18',
    messagingSenderId: '49238018761',
    projectId: 'boutiq-stage',
    storageBucket: "boutiq-stage.appspot.com",
    iosClientId:
        '49238018761-b7k2geqfis14pme1alrngjb87del44oc.apps.googleusercontent.com',
    iosBundleId: 'com.boutiq.provider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYA3mqo2xFsY5264huhA_A9n6-VaD84a8',
    appId: '1:49238018761:ios:18a5fae92089122ae71b18',
    messagingSenderId: '49238018761',
    projectId: 'boutiq-stage',
    storageBucket: "boutiq-stage.appspot.com",
    iosClientId:
    '49238018761-b7k2geqfis14pme1alrngjb87del44oc.apps.googleusercontent.com',
    iosBundleId: 'com.boutiq.provider',
  );
}
