// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoSK5dZa3UTdw4s8fUFVnt25tOyaqySRs',
    appId: '1:222019468081:web:c9f4d33677a88b816e8e10',
    messagingSenderId: '222019468081',
    projectId: 'tn-boutique-stage',
    authDomain: 'tn-boutique-stage.firebaseapp.com',
    storageBucket: 'tn-boutique-stage.appspot.com',
    measurementId: 'G-BNGYH61NLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx54l4amJlGPmmQcVOGDmwi5yxhqKaSfg',
    appId: '1:222019468081:android:7caec73e8a7293916e8e10',
    messagingSenderId: '222019468081',
    projectId: 'tn-boutique-stage',
    storageBucket: 'tn-boutique-stage.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi9ekVFoULhDmmkPjt990g19a8tMTM0z0',
    appId: '1:222019468081:ios:4be5e6e889b90e0b6e8e10',
    messagingSenderId: '222019468081',
    projectId: 'tn-boutique-stage',
    storageBucket: 'tn-boutique-stage.appspot.com',
    iosClientId: '222019468081-6mehohjvadnvli21f3kksm30jegu5k14.apps.googleusercontent.com',
    iosBundleId: 'com.tn.boutique.mobileTnBoutique',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi9ekVFoULhDmmkPjt990g19a8tMTM0z0',
    appId: '1:222019468081:ios:4be5e6e889b90e0b6e8e10',
    messagingSenderId: '222019468081',
    projectId: 'tn-boutique-stage',
    storageBucket: 'tn-boutique-stage.appspot.com',
    iosClientId: '222019468081-6mehohjvadnvli21f3kksm30jegu5k14.apps.googleusercontent.com',
    iosBundleId: 'com.tn.boutique.mobileTnBoutique',
  );
}
